[env:esp32-s3-devkitc-1]
platform = espressif32 @ 6.7.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

; Включаем PSRAM для ESP32-S3 (нужно для буфера экрана и больших гифок)
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -mfix-esp32-psram-cache-issue
    -O3

; Настройки для 8MB Flash и 8MB OPI PSRAM
board_upload.flash_size = 8MB
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions_8MB.csv
board_build.filesystem = littlefs
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L

lib_deps =
    mathieucarbou/ESPAsyncWebServer @ ^3.6.0
    mathieucarbou/AsyncTCP @ ^3.3.2
    bitbank2/AnimatedGIF @ ^2.1.1
    moononournation/GFX Library for Arduino @ 1.4.9
    bitbank2/JPEGDEC @ ^1.2.8
